export const CustomError = () => {
    throw new Error(
        'CustomError: This is a test error component for ErrorBoundary demonstration',
    );
};
